drop table if exists cartao cascade;
drop table if exists cliente cascade;
drop table if exists conta cascade;
drop table if exists fatura cascade;
drop table if exists pagamento cascade;
drop table if exists pessoa cascade;
drop table if exists transacao cascade;

CREATE TABLE IF NOT EXISTS cartao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_titular VARCHAR(255),
    numero VARCHAR(255),
    status VARCHAR(255) CHECK (status IN ('ATIVO', 'BLOQUEADO')),
    cvv VARCHAR(255),
    senha VARCHAR(255),
    atualizacao_limite DATE,
    conta_numero INTEGER,
    dia_vencimento INTEGER,
    limite NUMERIC(38,2),
    limite_diario NUMERIC(38,2),
    saldo NUMERIC(38,2),
    data_emissao TIMESTAMP(6),
    dtype VARCHAR(31) NOT NULL
);

CREATE TABLE IF NOT EXISTS cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    cpf VARCHAR(255),
    tipo VARCHAR(255) CHECK (tipo IN ('COMUM', 'SUPER', 'PREMIUM')),
    data_nascimento DATE,
    data_criacao TIMESTAMP(6),
    data_atualizacao TIMESTAMP(6),
    logradouro VARCHAR(255),
    numero VARCHAR(255),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(255),
    cep VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS conta (
    numero INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saldo NUMERIC(38,2),
    taxa_manutencao NUMERIC(38,2),
    taxa_rendimento FLOAT4,
    cliente_id BIGINT,
    data_criacao TIMESTAMP(6),
    data_atualizacao TIMESTAMP(6),
    ultima_movimentacao TIMESTAMP(6),
    dtype VARCHAR(31) NOT NULL,
    tipo_conta VARCHAR(255) CHECK (tipo_conta IN ('CORRENTE', 'POUPANCA'))
);

CREATE TABLE IF NOT EXISTS fatura (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cartao_id INTEGER,
    data_vencimento DATE,
    status SMALLINT CHECK (status BETWEEN 0 AND 1),
    mes_referencia BYTEA
);

CREATE TABLE IF NOT EXISTS pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE,
    fatura_id INTEGER,
    valor NUMERIC(38,2),
    loja VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS transacao (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   codigo UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
   conta_numero INTEGER,
   valor NUMERIC(38,2),
   data TIMESTAMP(6),
   descricao VARCHAR(255) CHECK (descricao IN (
        'TRANSFERENCIA_RECEBIDA',
        'TRANSFERENCIA_ENVIADA',
        'DEPOSITO_CAIXA_ELETRONICO',
        'SAQUE_CAIXA_ELETRONICO',
        'PAGAMENTO_FATURA',
        'COMPRA_DEBITO',
        'COMPRA_CREDITO',
        'PIX_RECEBIDO',
        'PIX_ENVIADO',
        'PAGAMENTO_PIX'
        )),
   tipo VARCHAR(255) CHECK (tipo IN (
        'ENTRADA', 'SAIDA'
   ))
);

alter table if exists cartao add constraint fk_cartao_conta foreign key (conta_numero) references conta;
alter table if exists conta add constraint fk_conta_cliente foreign key (cliente_id) references cliente;
alter table if exists fatura add constraint fk_fatura_cartao foreign key (cartao_id) references cartao;
alter table if exists pagamento add constraint fk_pagamento_fatura foreign key (fatura_id) references fatura;
alter table if exists transacao add constraint fk_transacao_conta foreign key (conta_numero) references conta;